# Schema documented at https://render.com/docs/yaml-spec
services:
  - type: web # valid values: https://render.com/docs/yaml-spec#type
    name: forwtekno
    repo: https://github.com/Mehavoid/forwtekno.git
    branch: master
    env: python # valid values: https://render.com/docs/yaml-spec#environment
    plan: free # optional; defaults to starter
    region: frankfurt # https://render.com/docs/regions
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m forwtekno"
    numInstances: 1
    envVars:
      - key: API_TOKEN
        sync: false
      - key: TO_CHANNEL
        sync: false
      - key: FROM_CHANNEL
        sync: false
      - key: TO_CAPTION
        sync: false
      - key: FROM_CAPTION
        sync: false
      - key: PYTHON_VERSION # https://render.com/docs/python-version
        value: 3.9.13
